# Generated by Django 5.2.4 on 2025-07-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_menuitem_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="pickup_time",
        ),
        migrations.RemoveField(
            model_name="order",
            name="stall",
        ),
        migrations.RemoveField(
            model_name="order",
            name="total_cost",
        ),
        migrations.RemoveField(
            model_name="order",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Ready", "Ready"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
