# Generated by Django 5.2.4 on 2025-07-15 20:35

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_order_created_at_remove_order_pickup_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_time",
            field=models.DateTimeField(default=core.models.default_pickup_time),
        ),
        migrations.AddField(
            model_name="order",
            name="stall",
            field=models.ForeignKey(
                default=core.models.get_default_stall,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.stall",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(
                default=core.models.default_transaction_id, max_length=50
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                default=core.models.get_default_user,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stall",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="stall_logos/"),
        ),
    ]
