# Generated by Django 5.2.4 on 2025-07-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_order_created_at_order_pickup_time_order_stall_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="blacklisted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=True),
        ),
    ]
