# Generated by Django 5.2.4 on 2025-07-16 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_orderitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "stall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vouchers",
                        to="core.stall",
                    ),
                ),
            ],
        ),
    ]
