# Generated by Django 5.2.4 on 2025-07-16 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_voucher"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="voucher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.voucher",
            ),
        ),
    ]
