# Generated by Django 5.2.4 on 2025-07-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_order_voucher"),
    ]

    operations = [
        migrations.AddField(
            model_name="stall",
            name="closing_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
