# Generated by Django 5.2.4 on 2025-07-16 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_stall_closing_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="stall",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stalls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
