# Generated by Django 5.2.4 on 2025-07-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_stall_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
    ]
