# Generated by Django 5.2.4 on 2025-07-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_stall_logo_stall_logo_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stall",
            name="logo_url",
        ),
        migrations.AddField(
            model_name="stall",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="stall_logos/"),
        ),
    ]
