# Generated by Django 5.2.4 on 2025-07-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_remove_stall_logo_url_stall_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stall",
            name="logo",
        ),
        migrations.AddField(
            model_name="stall",
            name="logo_filename",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
