# Generated by Django 5.2.4 on 2025-07-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_remove_stall_logo_stall_logo_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
